/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package View;

/**
 *
 * @author rafas
 */
public class menuView extends javax.swing.JFrame {

    /**
     * CRIAÇAO DO FORMULARIO DE MENU
     */
    public menuView() {
        initComponents();
        this.setExtendedState(menuView.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reservas para pousadas - Pousada Recanto da Maré");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JDesktopPane();
        LB_nome = new javax.swing.JLabel();
        LB_acesso = new javax.swing.JLabel();
        LB_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu_arquivos = new javax.swing.JMenu();
        s_menu_quartos = new javax.swing.JMenuItem();
        menu_reservas = new javax.swing.JMenu();
        s_menu_reservas = new javax.swing.JMenuItem();
        s_menu_clientes = new javax.swing.JMenuItem();
        menu_config = new javax.swing.JMenu();
        s_menu_usuario = new javax.swing.JMenuItem();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_nome.setBackground(new java.awt.Color(255, 255, 255));
        LB_nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LB_nome.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(LB_nome);
        LB_nome.setBounds(1170, 30, 50, 14);

        LB_acesso.setBackground(new java.awt.Color(255, 255, 255));
        LB_acesso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LB_acesso.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(LB_acesso);
        LB_acesso.setBounds(1230, 30, 120, 14);

        LB_id.setBackground(new java.awt.Color(255, 255, 255));
        LB_id.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(LB_id);
        LB_id.setBounds(1150, 30, 20, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/do-utilizador.png"))); // NOI18N
        menu.add(jLabel1);
        jLabel1.setBounds(1100, 20, 32, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/de-praia1.png"))); // NOI18N
        menu.add(jLabel2);
        jLabel2.setBounds(500, 70, 410, 530);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/image001-1menu.png"))); // NOI18N
        menu.add(jLabel6);
        jLabel6.setBounds(0, 0, 1460, 880);

        menu_arquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/abrir-pasta-com-documento.png"))); // NOI18N
        menu_arquivos.setMnemonic('e');
        menu_arquivos.setText("Arquivo");
        menu_arquivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/quarto.png"))); // NOI18N
        s_menu_quartos.setMnemonic('t');
        s_menu_quartos.setText("Quartos");
        s_menu_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_quartosActionPerformed(evt);
            }
        });
        menu_arquivos.add(s_menu_quartos);

        menuBar.add(menu_arquivos);

        menu_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/novo-documento.png"))); // NOI18N
        menu_reservas.setMnemonic('h');
        menu_reservas.setText("Reservas");
        menu_reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/reserva-on-line.png"))); // NOI18N
        s_menu_reservas.setMnemonic('c');
        s_menu_reservas.setText("Reservas");
        s_menu_reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_reservasActionPerformed(evt);
            }
        });
        menu_reservas.add(s_menu_reservas);

        s_menu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/silhueta-de-multiplos-usuarios.png"))); // NOI18N
        s_menu_clientes.setMnemonic('a');
        s_menu_clientes.setText("Clientes");
        s_menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_clientesActionPerformed(evt);
            }
        });
        menu_reservas.add(s_menu_clientes);

        menuBar.add(menu_reservas);

        menu_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/engrenagens-de-configuracoes.png"))); // NOI18N
        menu_config.setText("Configurações");
        menu_config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/bloquear-usuario.png"))); // NOI18N
        s_menu_usuario.setText("Usuários / Acessos");
        s_menu_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_usuarioActionPerformed(evt);
            }
        });
        menu_config.add(s_menu_usuario);

        menuBar.add(menu_config);

        menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/sair.png"))); // NOI18N
        menu_sair.setText("Sair");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        menuBar.add(menu_sair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_menu_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_quartosActionPerformed
        quartosView form = new quartosView();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_s_menu_quartosActionPerformed

    private void s_menu_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_usuarioActionPerformed
        funcionariosView form = new funcionariosView();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_usuarioActionPerformed

    private void s_menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_clientesActionPerformed
        clientesView form = new clientesView();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_clientesActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        this.dispose();
    }//GEN-LAST:event_menu_sairMouseClicked

    private void s_menu_reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_reservasActionPerformed
        reservasView form = new reservasView();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
        
        reservasView.txt_id_funcionario.setText(LB_id.getText()); //CAPTURA A "LB_id" LOGADA NO SISTEMA, POIS É UM FUNCIONARIO LOGADO.
        reservasView.txt_funcionario.setText(LB_nome.getText()); //CAPTURA A "LB_id" LOGADA NO SISTEMA, POIS É UM FUNCIONARIO LOGADO.

    }//GEN-LAST:event_s_menu_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LB_acesso;
    public static javax.swing.JLabel LB_id;
    public static javax.swing.JLabel LB_nome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JDesktopPane menu;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menu_arquivos;
    public static javax.swing.JMenu menu_config;
    private javax.swing.JMenu menu_reservas;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenuItem s_menu_clientes;
    private javax.swing.JMenuItem s_menu_quartos;
    private javax.swing.JMenuItem s_menu_reservas;
    private javax.swing.JMenuItem s_menu_usuario;
    // End of variables declaration//GEN-END:variables

}
