/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Apresentacao;

/**
 *
 * @author rafas
 */
public class frm_menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu
     */
    public frm_menu() {
        initComponents();
        this.setExtendedState(frm_menu.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reservas para Hotéis - Pousada Mazzaro");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JDesktopPane();
        LB_nome = new javax.swing.JLabel();
        LB_acesso = new javax.swing.JLabel();
        LB_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu_sistema = new javax.swing.JMenu();
        menu_arquivos = new javax.swing.JMenu();
        s_menu_quartos = new javax.swing.JMenuItem();
        menu_reservas = new javax.swing.JMenu();
        s_menu_reservas = new javax.swing.JMenuItem();
        s_menu_clientes = new javax.swing.JMenuItem();
        s_menu_pagamentos = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        menu_config = new javax.swing.JMenu();
        s_menu_usuario = new javax.swing.JMenuItem();
        menu_ferramentas = new javax.swing.JMenu();
        menu_ajuda = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_nome.setBackground(new java.awt.Color(255, 255, 255));
        menu.add(LB_nome);
        LB_nome.setBounds(1240, 30, 50, 14);

        LB_acesso.setBackground(new java.awt.Color(255, 255, 255));
        LB_acesso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.add(LB_acesso);
        LB_acesso.setBounds(1300, 30, 120, 14);

        LB_id.setBackground(new java.awt.Color(255, 255, 255));
        menu.add(LB_id);
        LB_id.setBounds(1220, 30, 20, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/do-utilizador (1).png"))); // NOI18N
        menu.add(jLabel1);
        jLabel1.setBounds(1170, 20, 32, 40);

        menu_sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/casa.png"))); // NOI18N
        menu_sistema.setMnemonic('f');
        menu_sistema.setText("Sistema");
        menu_sistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_sistema);

        menu_arquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/abrir-pasta-com-documento.png"))); // NOI18N
        menu_arquivos.setMnemonic('e');
        menu_arquivos.setText("Arquivo");
        menu_arquivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/quarto.png"))); // NOI18N
        s_menu_quartos.setMnemonic('t');
        s_menu_quartos.setText("Quartos");
        s_menu_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_quartosActionPerformed(evt);
            }
        });
        menu_arquivos.add(s_menu_quartos);

        menuBar.add(menu_arquivos);

        menu_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/novo-documento.png"))); // NOI18N
        menu_reservas.setMnemonic('h');
        menu_reservas.setText("Reservas");
        menu_reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/reserva-on-line.png"))); // NOI18N
        s_menu_reservas.setMnemonic('c');
        s_menu_reservas.setText("Reservas");
        s_menu_reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_reservasActionPerformed(evt);
            }
        });
        menu_reservas.add(s_menu_reservas);

        s_menu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/silhueta-de-multiplos-usuarios.png"))); // NOI18N
        s_menu_clientes.setMnemonic('a');
        s_menu_clientes.setText("Clientes");
        s_menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_clientesActionPerformed(evt);
            }
        });
        menu_reservas.add(s_menu_clientes);

        s_menu_pagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/forma-de-pagamento.png"))); // NOI18N
        s_menu_pagamentos.setText("Pagamentos");
        menu_reservas.add(s_menu_pagamentos);

        menuBar.add(menu_reservas);

        menu_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/analitico.png"))); // NOI18N
        menu_consultas.setText("Consultas");
        menu_consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_consultas);

        menu_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/engrenagens-de-configuracoes.png"))); // NOI18N
        menu_config.setText("Configurações");
        menu_config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/bloquear-usuario.png"))); // NOI18N
        s_menu_usuario.setText("Usuários / Acessos");
        s_menu_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_usuarioActionPerformed(evt);
            }
        });
        menu_config.add(s_menu_usuario);

        menuBar.add(menu_config);

        menu_ferramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/ferramenta-de-reparacao.png"))); // NOI18N
        menu_ferramentas.setText("Ferramentas");
        menu_ferramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_ferramentas);

        menu_ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/pergunta.png"))); // NOI18N
        menu_ajuda.setText("Ajuda");
        menu_ajuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_ajuda);

        menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones2/sair.png"))); // NOI18N
        menu_sair.setText("Sair");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        menuBar.add(menu_sair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_menu_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_quartosActionPerformed
        frm_quartos form = new frm_quartos();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_s_menu_quartosActionPerformed

    private void s_menu_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_usuarioActionPerformed
        frm_funcionarios form = new frm_funcionarios();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_usuarioActionPerformed

    private void s_menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_clientesActionPerformed
        frm_clientes form = new frm_clientes();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_clientesActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        this.dispose();
    }//GEN-LAST:event_menu_sairMouseClicked

    private void s_menu_reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_reservasActionPerformed
        frm_reservas form = new frm_reservas();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
        
        frm_reservas.txt_id_funcionario.setText(LB_id.getText()); //CAPTURA A "LB_id" LOGADA NO SISTEMA, POIS É UM FUNCIONARIO LOGADO.
        frm_reservas.txt_funcionario.setText(LB_nome.getText()); //CAPTURA A "LB_id" LOGADA NO SISTEMA, POIS É UM FUNCIONARIO LOGADO.

    }//GEN-LAST:event_s_menu_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LB_acesso;
    public static javax.swing.JLabel LB_id;
    public static javax.swing.JLabel LB_nome;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JDesktopPane menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menu_ajuda;
    public static javax.swing.JMenu menu_arquivos;
    public static javax.swing.JMenu menu_config;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_ferramentas;
    private javax.swing.JMenu menu_reservas;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_sistema;
    private javax.swing.JMenuItem s_menu_clientes;
    private javax.swing.JMenuItem s_menu_pagamentos;
    private javax.swing.JMenuItem s_menu_quartos;
    private javax.swing.JMenuItem s_menu_reservas;
    private javax.swing.JMenuItem s_menu_usuario;
    // End of variables declaration//GEN-END:variables

}
